### ISSUE TITLE
進捗状況報告

### ISSUE THREAD

**Issue by mznmk** [mznmk/libunit#4]
ここに現在の進捗状況を適宜報告していきましょう！

**Comment by mznmk** [comment]
branch "mika" を作成しました。
frameworkに対応シグナルを増やしました。
テスト結果の表示部分を微妙に修正しました。
修正内容を master branch に merge しました。

**Comment by mznmk** [comment]
- framework の signal SIGALRM を使ったTimeout処理の実装方法を考え中です。
Mandatoryの利用可能関数だけでは無理そうなので、Bonusコンパイルに切り分けるかもしれません。
- tests の BusErrorを起こす関数を考え中です。
- あらたさんが考えてくれた ft_strlenのテスト案とプラスアルファを考え中です。

**Comment by mznmk** [comment]
こちらの環境がUbuntu20.04で、Mac/Guacamoleでのチェックは全然やっていません。
どこかのタイミングでしないといけませんね。

**Comment by mznmk** [comment]
他のタスクより先に、real-tests にlibft Mandatory part 全関数の雛形を作っていきます。
strlenに縛られることなく、選択肢を広げるのもいいかと思いました。

**Comment by mznmk** [comment]
real-tests に ft_atoi を追加しました。
mergeしても問題ないでしょうか？

**Comment by arata-7** [comment]
> 1ファイル 1関数ではなく、1ファイル1テスト関数（test function ）なのでヘルパー関数を追加しても問題ないです。

テスト関数に関数を二つ以上書いても大丈夫とのことです。

**Comment by mznmk** [comment]
> real-tests に ft_atoi を追加しました。
> mergeしても問題ないでしょうか？
mergeして、GitHubにpush しました。1e9048f7365c400ba1d8bfb76d0023ec4021a41b
その後のcommit で ft_memmove も追加してあります。

**Comment by arata-7** [comment]
ローカル環境でreal-testsに ft_strlenのテスト関数を追加しました。

普段の個人開発だと下記手順でリポジトリに提出しています。
git add.
git commit -m"コメント"
git push origin master

今回の場合だとarata ブランチにいる状態で下記手順でcommit からmergeまで行う理解で大丈夫でしょうか？
git add.
git commit -m"コメント"
git push origin arata
git checkout master
git pull origin arata

**Comment by mznmk** [comment]
せっかく連絡してくれたのに申し訳ありません。寝落ちしてました。

> 水野さんの commit 1e9048f と私のプルリクエストでMakefileなどににconflictが発生している状態です。

共同で開発しているのに、配慮が足りず、不必要に変更しすぎてしまったかもしれません。すみません。
至急確認します。

**Comment by arata-7** [comment]
コンフリクトしていている内容を私のvscode上で確認しローカルで編集し再度pushしたところconflictが解消されました。

tests-folder/Makefileのatoiやmemmoveのテスト関数が私のブランチを切った時にはまだ追加されておらずその状態でft_strlenのテスト関数を追加したためコンフリクトがおこったみたいです。

コンフリクトした際に下記手順でコンフリクト解消して再度pushするようにします。

1. コンフリクトしたファイルはmaster側の更新内容を反映させる(自分の更新内容は消える)
2. git commit でコンフリクトを解消する
3. コンフリクトしたファイルに自分の更新内容を反映させる(git diffなどで差分を見ながら行う)
4. 自分の更新内容をcommitする
5. git push origin 開発用ブランチ

お騒がせして失礼しました。

**Comment by mznmk** [comment]
おお〜すごい！
私どうしたらいいかわからなくて悩んでました。
解決してくれてありがとうございます！

こちらも何も考えずにファイル名を変更したり、いろいろやらかしてしまってました。
今後の反省材料です。

**Comment by mznmk** [comment]
確かプルリクって、リポジトリに対しての権限がない人がするものだったような…。
フォークして変更した内容を、「反映して〜」とリクエストする、という理解をしています。
今回はリポジトリに対する権限を渡しているので、OKできちゃったんじゃないか？って思いました。

**Comment by arata-7** [comment]
なるほど。その可能性ありますね！
権限があるときでもプルリクを使うべきなのか、issueなどで許可を取って自分でmergeすべきかお作法的にはどちらが正しいか分からないのでとりあえず探り探り進めていきます。

**Comment by mznmk** [comment]
gcc の -g -fsanitize=address ではリークを検知しないのに、valgrind では still reachable がでる。
これがメモリリークなのかが正直わからない状態です。リークしてたらアウトだと思うので解決したいです。
これ、issueとして立てます。

**Comment by mznmk** [comment]
real-tests に libft Mandatory Part1(libc functions) のテストを全部追加しようと無謀なことを一瞬考えたのですが、その時にひな型部分までを作成しました。Discord のDMで送りますので、良ければ使ってください。
なお、ファイル名のダブリを防ごうと、一部 `ft_atoi/00_atoi_launcher.c` のようになってますのでご注意ください。

**Comment by arata-7** [comment]
【進捗状況 ワカモレでの動作確認】

- コンパイルエラーが出ていたのでissue #9 を立てました。ご確認のほどよろしくお願いします。

【進捗状況 is系の関数追加】

real-tests/ に下記テスト関数を追加しました。
- isalnum isalpha isascii isdigit isprint
- toupper tolower

水野さんのコミットを確認後に追加したテスト関数をpushします。

**Comment by mznmk** [comment]
遅くなってすみません。
取り急ぎ、GitHub に pushしました。
確認お願いします！

今から「SIGABORT / SIGFTP / SIGBUS の実装方法をようやく思いつきました。」の部分をやっていきます！

**Comment by arata-7** [comment]
水野さんのブランチを確認したところ最新のcommitが2days agoと表示されていました。もしかするとまだpushできていないかもしれないのでもう一度確認いただけますか。

お手数ですがよろしくお願いいたします。

**Comment by mznmk** [comment]
結論からですが、master にしか push してませんでした。
行った手順は次の通りです。

1. git pull してローカルのmaster branch を更新
2. ローカルで変更を加えたmika branch を master branch にマージ
3. それをGitHub の master branch に push
4. master branch がちゃんと更新されたかを確認

mika branch を push してなかったので、たった今 push を行いました。
心配かけてすみません。

**Comment by mznmk** [comment]
いっぱいテストを追加してくれてありがとうございます。

…なのに、こちらはさぼってしまって、進捗ゼロでした。すみません。
明日午前中にtests終わらせます！

**Comment by mznmk** [comment]
- [tests] BusErrorがおこるようにできた
- [GitHub Actions] master branch だけではなく、arata / mika branch でもテストが走るようにした。

- https://github.com/mznmk/libunit/runs/2570799074?check_suite_focus=true

**Comment by arata-7** [comment]
> BusError は strlcpy の trueテストで発生させる予定です。
> "42Tokyo" のような定数に上書きしたら、MacではBusErrorが発生するはずなので。
> LinuxだとSegmentationFaultになりますけど。

Bus対応ありがとうございます。Linuxでbuserror表示させないといけないと思ってたんですが、
課題分に下記記載があったので確かにMacで表示できれば大丈夫そうですね!!よかったです

> This project should compile on 42Tokyo’s iMac or on Guacamole.

**Comment by mznmk** [comment]
- [tests] Bonus のテスト関数を完全に Mandatory -> Bonus に切り分けました。
- [tests] ft_atoi_overflow では FPE を発生させれなかったので、符号間違いでゼロ除算がおこるように変更し、ft_atoi_dividebyzeroと関数名を変更しました。それに伴い、関連する名称も変更しました。
- [real-tests] Makefile に test_bonus というルールを追加しました。
- [framework] timeout delay が長かったので、5s -> 3s に変更しました。

**Comment by mznmk** [comment]
mergeしてmaster branch にpushしてしまいました
勝手にやっちゃってすみません

**Comment by mznmk** [comment]
- [tests][real-tests] ABRT を発生させるのに double free させたらターミナルにエラーメッセージが表示されるバグを修正しました。
- [tests][real-tests] main() の戻り値を-1 -> 1()に変更しました。

**Comment by arata-7** [comment]
水野さんのtests/atoi のテスト関数追加前ですが、

tests/
- make test / make test_bonus の表示結果確認
- normV3 確認

framework
- normV3 確認

を実施し問題ないことを確認できました。

**Comment by mznmk** [comment]
- [tests] に ft_atoi のテスト29個を追加しました。
- [real-tests][tests] main() の戻り値を 1 -> -1 に戻しました。(本科Discordのやり取りから)
- norm3 対応をしました。（したつもりですが、念の為確認願います）
- GitHubからlocal masterにpull してきて、それにlocal mikaをマージして、GitHubにpush し直しました
- real-tests/main.c でコンフリクトしたので、修正しました。

**Comment by mznmk** [comment]
いまから real-tests を見ていきます。
