### ISSUE TITLE
real-tests/strlen に加えるテスト関数

### ISSUE THREAD

**Issue by arata-7** [mznmk/libunit#5]
strlenに加えるテスト関数候補以下記載します。
現状12種類あり15種類には後3つ追加する必要があります。
12種類のテスト関数は(OK, KO, SEGV, BUSE)の結果を全て少なくとも一回表示します。
数を増やすために無理やり作ったテストケースもあるので不要なものなどあればコメントお願いします。

**-OKを返す**
1. basic_test.c \ ft_strlenとstrlenを比較して結果を返す
2. long_str_test.c \ 長い文字列（1000文字以上）を引数にとりft_strlenとstrlenを比較して結果を返す
3. only_escaped_character_test.c \ エスケープされた文字のみを含む文字列（"\"\\\"\'"）を引数にとりft_strlenとstrlenを比較して結果を返す
4. escaped_character_and_normal_character_test.c \ エスケープされた文字を含む文字列（"\"bbbb\\aaaa\"\'"）を引数にとりft_strlenとstrlenを比較して結果を返す
5. only_space_character_test.c \ 空白文字のみを含む文字列（"\t\v\r\f\n"）を引数にとりft_strlenとstrlenを比較して結果を返す
6. space_character_and_normal_character_test.c \ 空白文字を含む文字列（"aaa\t\vbbbb\r\fccccc\n"）を引数にとりft_strlenとstrlenを比較して結果を返す
7. only_terminated_character_test.c \ 終端文字のみの文字列（"\0"）を引数にとりft_strlenとstrlenを比較して結果を返す
8.  miltiple_terminated_characters_test.c \ 終端文字を複数含む文字列（"aaaa\0bbb\0ccc"）を引数にとりft_strlenとstrlenを比較して結果を返す
9. unicode_character_test.c \ uniode文字のみの文字列を引数にとり（"ああああああ"）ft_strlenとstrlenを比較して結果を返す

**-KOを返す**
10.basic_ko_test.c \ ft_strlenとstrlenはそれぞれ異なる文字数の文字列を引数をとり比較して結果を返す
(例)
if（ft_strlen("AAA") ==strlen("BBBB") ）
      KO
else
      OK

**- SEGVを表示する**
11. null_test.c \ 引数にNULLをとりft_strlenとstrlenを比較して結果を返す

**- BUSEを表示する**
12. buserror_test.c \ 引数に文字列リテラルをとり（"aaaaaaaaa"）ft_strlen_busserrorとstrlenを比較して結果を返す（ft_strlen_busserrorでは文字列領域への不正アクセスを行う）

**Comment by mznmk** [comment]
たくさんテスト案をつくっていただき、ありがとうございます。
内容は今から精査していきますが、その前に１点だけ。

> 12種類のテスト関数は(OK, KO, SEGV, BUSE)の結果を全て少なくとも一回表示します。

と、あるのですが、(OK, KO, SEGV, BUSE)の４パターンのテスト関数が必要なのはtestsフォルダーだけではないかと思いました。(subject V4 Your results 参照)

**Comment by mznmk** [comment]
https://github.com/alelievr/libft-unit-test
https://github.com/jtoty/Libftest

**Comment by mznmk** [comment]
Level0のlibftテスターを確認したのですが、ft_strlenだと多くのテストを作るのが難しいような気がしました。
上のリンクにテスト画面のスクリーンショットがあるのですが、それによると、
ft_memmove
ft_strncmp
ft_strnstr
ft_atoi
このあたりのテスト項目が多そうです。

**Comment by mznmk** [comment]
libft-unit-test の test_function.c
https://github.com/alelievr/libft-unit-test/blob/master/src/test_functions.c
Libftest の test_functions
https://github.com/jtoty/Libftest/tree/master/tests/Part1_functions

**Comment by arata-7** [comment]
確認ありがとうございます。

"15種類のテスト関数を作成する" が1つの関数に対して15個だった場合を想定して15個作成しようと思ったのですがft_strlenだとこれ以上増やすのは厳しそうなので、提案頂いたatoiのテスト関数も追加し strlenとatoiのテスト関数を合計して15個以上作成するようにします。

**Comment by arata-7** [comment]
送って頂いたdiscordのリンクで問題文の解釈理解できました。

問題文の解釈にも納得感があるのでこちらで進めていきましょう。
ひとまず私からはft_strlenのフォルダにテストケースを12種類追加したのでこちらをpushしようと思います。
本来testsに入るべき KO, SEGV, BUSEのテストケースもreal-testsに入っていますが、送って頂いた問題解釈に合うように別のcommitでファイルを移動させます。

**Comment by arata-7** [comment]
commit c023bec でft_strlenのテスト関数を追加。

**Comment by mznmk** [comment]
あらたさんが master に merge してくれたものをpull してきて試してみました。
たくさんテストを作ってくれてありがとうございます。

libft の ft_strlenを修正したら結果がテストの結果が変わって、
「本物のテストなんだ…」と感動しました。こういうの楽しいですね。

動作させてみた感想なのですが…

- real-tests に意図的にエラーを起こすテストは必要ないのでは？
そういうテストは tests に追加したらいいのではないかと思いました。

- buserror test
インラインアセンブラ(asm関数)を使ってるのでMandatoryではアウトになりそうです。 

- basic KO test
falseテストなので、success / failure が逆な気がしました。
`if (ft_strlen("aaaa") != strlen("bbbbb"))` もしくは returnの値を逆にすると解決できそうです。

**Comment by arata-7** [comment]
> basic KO test
> falseテストなので、success / failure が逆な気がしました。
> if (ft_strlen("aaaa") != strlen("bbbbb")) もしくは returnの値を逆にすると解決できそうです。

このテストはKOと表示できるか確認するためだけ関数として作成しました。エラーを吐かせる関数という意味では、testsに追加すべきテスト関数なのかなと。

本来のテスターの機能として考えると結果が違っていたらOKなので 確かに逆にした方が良いですね。
returnの値を逆にしたものをreal-testsに残し、
現状のbasic KO testはSEGV BUSE と同じようにtestsに移動させようと思っているのですがいかがでしょうか。

**Comment by mznmk** [comment]
「tests に追加したらいいのではないか」と発言したものの、testsの内容を見直すと、[OK][KO][SEGV]はすでに実装してありましたので、追加しなくて大丈夫そうです。
[BUSE]については、その続きで、[BUSE]もこちら側で実装していこうと思いますが、いかがでしょうか。

```
| || |__ \| |  | |     (_) |__   __|      | |      
| || |_ ) | |  | |_ __  _| |_ | | ___  ___| |_ ___ 
|__   _/ /| |  | | '_ \| | __|| |/ _ \/ __| __/ __|
   | |/ /_| |__| | | | | | |_ | |  __/\__ \ |_\__ \
   |_|____|\____/|_| |_|_|\__||_|\___||___/\__|___/
=================
| < ft_strlen > |
===================================================
TRUE Test - returns OK                   : [ OK ]
FALSE Test - returns OK                  : [ OK ]
TRUE Test - returns SEGV                 : [ SEGV ]
---------------------------------------------------
[ success:  2 failure:  1 / total:  3 ]  : [ KO ]
===================================================
======================
| < ft_strlen_segv > |
===================================================
TRUE Test - returns OK                   : [ KO ]
FALSE Test - returns OK                  : [ OK ]
TRUE Test - returns SEGV                 : [ SEGV ]
---------------------------------------------------
[ success:  1 failure:  2 / total:  3 ]  : [ KO ]
===================================================
```
---
Bonus項目として tests に追加を予定しているのは、次の３つです。
[ABORT] -> ダブルフリー
[FPE] -> ゼロ除算
[ALERM] -> タイムアウト （signal() が必要そう）
タイムアウトについては、Mandatoryの関数縛りでは無理な部分があるので、frameworkにちょっと大きめの変更を加えようと思いますが、いかがでしょうか？

**Comment by arata-7** [comment]
課題文を改めて眺めていたところV.2 The tests にある下記記載が少し気になったのでこちらに記載しておきます。

Each test function must be in the folder tests.

この記述だと全てのテスト関数はtests フォルダーに配置されている必要があるようです。
なので最終的には下記フォルダ構成になるように調整する必要がありそうです。

real-tests → libft
tests → 全てのテスト関数（エラーを吐くテスト関数と通常のテストのためのテスト関数）

覚書として残しておきます。

**Comment by mznmk** [comment]
！！！
全然気づきませんでした。ありがとうございます。
よく考えたら、そろそろ提出に向けてあわせていかないといけない時期ですよね。

これ、別にissue立てますね！
