### ISSUE TITLE
valgrind で still reachable が消えない

### ISSUE THREAD

**Issue by mznmk** [mznmk/libunit#8]
gcc のオプションで -g -fsanitize=address をつけてコンパイルして実行しても何も発生しないので、メモリリークは起こっていないと思っていました。
ところが、valgrind でのチェックを行ったところ、still reachable が発生しました。普段 valgrind を使わないので、これがメモリリークなのかわからない状態です。
メモリリークが発生するとクリアできないと思うので、正直焦っています。
確認してもらえると嬉しいです。

（普段 valgrind を使っていないのに、なぜ使おうと思ったかというと、GitHub Actions で メモリリークテストを行うためでした。手動でMakefileにオプションをつける作業は自動化できないので…。）

---

行った工程は次の通りです。
```
cd ./real-tests
make re
valgrind --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all ./real-tests
```
このようなエラーメッセージがでました。
```
==66702== LEAK SUMMARY:
==66702==    definitely lost: 0 bytes in 0 blocks
==66702==    indirectly lost: 0 bytes in 0 blocks
==66702==      possibly lost: 0 bytes in 0 blocks
==66702==    still reachable: 72 bytes in 3 blocks
==66702==         suppressed: 0 bytes in 0 blocks
==66702== 
==66702== For lists of detected and suppressed errors, rerun with: -s
==66702== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
Positive number (digit==1)               : [ KO ]
==66703== 
==66703== HEAP SUMMARY:
==66703==     in use at exit: 72 bytes in 3 blocks
==66703==   total heap usage: 5 allocs, 2 frees, 120 bytes allocated
==66703==
```

理由が知りたかったので、
`--gen-suppressions=all ` をつけて再度 valgrind を実行したところ、次のメッセージが出ました。
```
==49394== 
{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: reachable
   fun:malloc
   fun:create_unittest
   fun:add_unittest
   fun:atoi_launcher
   fun:execute_tests
   fun:main
}
```
unittest を格納するリストを create するところで発生しているようですが、コードを確認してもリークが発生するような感じには思えなくて…。
確認していただけないでしょうか？

**Comment by mznmk** [comment]
> still reachable
> 
> プログラムが終了する前に free/delete されなかった領域が存在する場合に still reachable と出力されます。プログラム自体が終了しているため definitely lost の場合と異なりメモリリークとして問題になることはありません。

https://www.qoosky.io/techs/0d625ea736

問題ないらしいです。お騒がせしました。

**Comment by arata-7** [comment]
色々と確認いただきありがとうございます。

still reachable問題ないみたいですね.
discordのチャットで同じ話題があるのを見つけました。

https://discord.com/channels/691903146909237289/751666315386945689/807279183163162696

問題ないことがわかった上でcub3dの時にstill reachableが消せたのと同じように、今回も消せないかコードを触っていたのですが成果なしでした。

**Comment by mznmk** [comment]
いろいろ調べていただいてありがとうございます。
ということは、解決ということにしてissueを閉じてもいい感じ…でしょうか？
大丈夫そうだと判断したら、閉じてもらって構わないです。
