### ISSUE TITLE
Guwacamole での動作確認

### ISSUE THREAD

**Issue by arata-7** [mznmk/libunit#9]
Guwacamoleでcommit b2ab4f8 までのコードでmake testを実行したところ下記エラーメッセージが出力されてコンパイルが途中で中断しました。

`
gcc -Wall -Wextra -Werror  -I ./includes/ -c sources/mandatory/ft_strjoin.c -o sources/mandatory/ft_strjoin.o
gcc -Wall -Wextra -Werror  -I ./includes/ -c sources/mandatory/ft_strtrim.c -o sources/mandatory/ft_strtrim.o
gcc -Wall -Wextra -Werror  -I ./includes/ -c sources/mandatory/ft_split.c -o sources/mandatory/ft_split.o
sources/mandatory/ft_split.c:85:19: error: 
expression which evaluates to zero treated as a null pointer constant of type 'char *'
      [-Werror,-Wnon-literal-null-conversion]
 dests[dests_i] = '\0';
                         ^~~~
1 error generated.
make[1]: *** [sources/mandatory/ft_split.o] Error 1
make: *** [real-tests] Error 2`

libftのft_split.cでコンパイルエラーが出ているようです。
エラーが出ている部分のコードを下記に変更したところコンパイルが通り結果が表示されました。

`
dests[dests_i] = NULL;
`

上記ご確認の程よろしくお願いします。

**Comment by mznmk** [comment]
テストしてくれてありがとうございます。
GitHub Actions の動作を macos-latest に変更したら、そちらでも同じエラーが出ていました。
https://github.com/mznmk/libunit/runs/2562340725?check_suite_focus=true

修正してくれてありがとうございました。
